version: '3'
services:
  web_scraping_service:
    build:
      context: ./backend/web_scraping_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - text_summarization_service
    environment:
    - SUMMARIZATION_SERVICE_URL=http://text_summarization_service:8081/summarize/

  text_summarization_service:
    build:
      context: ./backend/text_summarization_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
    - OPEN_AI_KEY=CHECK_CONFIG_PY
